### ISSUE TITLE
Q4 Remove

### ISSUE THREAD

**Issue by dianjiaogit** [ClayFx/COMP1110-Final-Sample#2]
第四题里那个remove其中的
`System.arraycopy(values,index + 1, values,index,elements - index - 1);`
是什么意思呀？

我是这样写的
`public void remove(int index) {
        /* Unimplemented. Q4 ii) [7 Marks] */
        if (index < 0 || index >= values.length || elements == 0) {
            throw new IndexOutOfBoundsException();
        }
        T[] a = values;
        values = Arrays.copyOf(values, index);
        values = Arrays.copyOf(values, elements);
        for (int i = index + 1; i < elements; i++) {
            values[i - 1] = a[i];
        }
        elements -= 1;
    }`

**Comment by ClayFx** [comment]
把原array复制到新array的指定index
